### ISSUE TITLE
Break-up Package For Easier Download & Updates

### ISSUE THREAD

**Issue by The-Don-Himself** [leifoolsen/mdl-ext#74]
Hi @leifoolsen,

Thank you for such a wonderful set of mdl-extensions. I am gradually introducing some into my public-beta [app](https://campus-discounts.com)

Now, I'm based in Kenya, where internet is more often than not very flaky. Downloading your zip is 20MB. It can take me anywhere between 30mins to 1hr when net misbehaves which is very often. And thats using Internet Download Manager.

Is it possible to have the pre-compiled assets as a separate zip file? Because that would be less than 1MB and would allow for easier downloading and upgrading.

Regards.

**Comment by leifoolsen** [comment]
Hello @The-Don-Himself 

Thank you for reporting this. 

Size of the library has not been in my thoughts, probably because we are used (spoiled) with high speed internet lines.

I would certainly consider modularize the library, but this is unfortunately something ahead. I probably will not put any work in this before MDL verson 2 arrives.

What I possibly can do relatively quickly is to split demo application into a separate repo. Since the demo application contains many larger image files, I think such a split is something that can increase download speed. But at the same time, a split will make it harder to test components visually, so I have to find a solution that does not impede visual testing  Unfortunately, I can not give any timing for such a split since my time is filled up with the development of new (WAI-ARIA friendly) components. Among other things, I will soon have completed a menu-button component which is in accordance to WAI-ARIA Authoring Practices [section 2.20] (https://www.w3.org/TR/wai-aria-practices/#menubutton)

BTW: The site you're building looks nice 👍

**Comment by leifoolsen** [comment]
![screen shot 2016-09-25 at 03 37 27](https://cloud.githubusercontent.com/assets/10088486/18812341/9c65e8e2-82d1-11e6-995a-51b27b9360da.png)

**Comment by The-Don-Himself** [comment]
Hi @leifoolsen,

Thank you for considering this issue and more so for your compliments on my site, again worth noting that is only possible from gracious libraries like mdl and mdl-ext.

Splitting the demo into a separate repo makes sense but I wouldn't want a solution that increases the workload on your part especially since I'm sure low-speed-internet devs (if there such a term!) are in the vast minority and also because it seems you're the sole dev behind mdl-ext.

So I think this can wait until you have the time, or when the library grows with more contributors who can take on such tasks.  Will close this for now but please keep it in mind for later. Thanks.

**Comment by The-Don-Himself** [comment]
Hi @leifoolsen ,

Some what related issue. Building a web app that currently only requires mdl-ext accordion component. Is there any way to achieve/build that without the entire pack?

On a side note, I the relatively new menu buttons are awesome!

Cheers.

**Comment by leifoolsen** [comment]
@The-Don-Himself : Will fix this i release 0.13.11. The release will be significantly smaller. Will also document how to require a specific component (using webpack)

**Comment by The-Don-Himself** [comment]
@leifoolsen That is awesome thanks, can't wait :1st_place_medal:

**Comment by leifoolsen** [comment]
MDLEXT will now come with a separate ES2015 directory that enables loading of individual components. I have also included an example that shows the use of this.

About the accordion: We have used this component in two different projects @ work and it begins to reveal some weaknesses in the way it is programmed. A refactoring of code will be required. There will probably be changes in CSS class names and markup structure. JavaScript code will be broken down into smaller modules, partly to prepare for MDL-2
